name: Publish

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-publish:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Publish
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: docs
        single-commit: true
